language: clojure
lein: lein2
before_script:
  - npm install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
 - lein2 cljsbuild once test
 - ./node_modules/.bin/karma start karma.conf.js --single-run
jdk:
  - oraclejdk8
