language: clojure
before_script:
  - npm install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
 - lein cljsbuild once test
 - ./node_modules/.bin/karma start config/run.conf.js
 - ./node_modules/.bin/karma start config/run-all.conf.js
 - ./node_modules/.bin/karma start config/run-all-regex.conf.js
jdk:
  - oraclejdk8
